# version: '3'
# services:
#   jekyll:
#     image: jekyll/jekyll:3.8
#     environment:
#       - JEKYLL_ENV=development
#     command: bundle update jekyll && bundle install && bundle exec jekyll serve --watch --incremental --config _config-dev.yaml --host 0.0.0.0 --drafts
#     ports:
#       - 4000:4000
#     volumes:
#       - .:/srv/jekyll:cached
#       - ./vendor/bundle:/usr/local/bundle:cached

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose --livereload
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll